[package]
name = "llamareader-python"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
categories.workspace = true
include = ["/src"]

[dependencies]
llamareader = { path = "../core", features = ["python"] }
pyo3 = { version = "0.22.2", features = ["extension-module"] }
