[package]
name = "llamareader-node"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
categories.workspace = true
include = ["/src"]

[lib]
crate-type = ["cdylib"]

[dependencies]
llamareader = { workspace = true, features = ["node"] }
napi = { version = "3.0.0-alpha.8", default-features = false, features = ["napi9"] }
napi-derive = "3.0.0-alpha.6"

[build-dependencies]
napi-build = "2.1.3"
