/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Metadata {
  title: string
}
export interface Page {
  content: string
  mime: string
}
export interface Epub {
  metadata: Metadata
  pages: Array<Page>
}
function readEpub(path: string): Epub
